<?php

namespace ContainerUaBc4UP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M80PlgMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M80PlgM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entrepriseRepository' => ['privates', 'App\\Repository\\EntrepriseRepository', 'getEntrepriseRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'entrepriseRepository' => 'App\\Repository\\EntrepriseRepository',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.M80PlgM'])) {
            return $container->privates['.service_locator.M80PlgM'];
        }

        return $container->privates['.service_locator.M80PlgM'] = $instance;
    }
}
