<?php

namespace ContainerUaBc4UP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QPHIqLbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qPHIqLb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'document' => ['privates', '.errored..service_locator.qPHIqLb.App\\Entity\\Document', NULL, 'Cannot autowire service ".service_locator.qPHIqLb": it needs an instance of "App\\Entity\\Document" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'historyService' => ['privates', 'App\\Service\\HistoryService', 'getHistoryServiceService', true],
        ], [
            'dispatcher' => '?',
            'document' => 'App\\Entity\\Document',
            'entityManager' => '?',
            'historyService' => 'App\\Service\\HistoryService',
        ]);

        if (isset($container->privates['.service_locator.qPHIqLb'])) {
            return $container->privates['.service_locator.qPHIqLb'];
        }

        return $container->privates['.service_locator.qPHIqLb'] = $instance;
    }
}
