<?php

namespace ContainerUaBc4UP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B6X8ggtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B6X8ggt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aiService' => ['privates', 'App\\Service\\AIService', 'getAIServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'entrepriseRepository' => ['privates', 'App\\Repository\\EntrepriseRepository', 'getEntrepriseRepositoryService', true],
        ], [
            'aiService' => 'App\\Service\\AIService',
            'entityManager' => '?',
            'entrepriseRepository' => 'App\\Repository\\EntrepriseRepository',
        ]);

        if (isset($container->privates['.service_locator.B6X8ggt'])) {
            return $container->privates['.service_locator.B6X8ggt'];
        }

        return $container->privates['.service_locator.B6X8ggt'] = $instance;
    }
}
