<?php

namespace ContainerUaBc4UP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GFYs6KSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gFYs6KS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gFYs6KS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entreprise' => ['privates', '.errored..service_locator.gFYs6KS.App\\Entity\\Entreprise', NULL, 'Cannot autowire service ".service_locator.gFYs6KS": it needs an instance of "App\\Entity\\Entreprise" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entreprise' => 'App\\Entity\\Entreprise',
        ]);
    }
}
