<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW0bl9yW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW0bl9yW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW0bl9yW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW0bl9yW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW0bl9yW\App_KernelDevDebugContainer([
    'container.build_hash' => 'W0bl9yW',
    'container.build_id' => 'b1c8403c',
    'container.build_time' => 1771991959,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW0bl9yW');
