<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E5wFl3GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e5wFl3G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'entreprise' => ['privates', '.errored..service_locator.e5wFl3G.App\\Entity\\Entreprise', NULL, 'Cannot autowire service ".service_locator.e5wFl3G": it needs an instance of "App\\Entity\\Entreprise" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'entreprise' => 'App\\Entity\\Entreprise',
        ]);

        if (isset($container->privates['.service_locator.e5wFl3G'])) {
            return $container->privates['.service_locator.e5wFl3G'];
        }

        return $container->privates['.service_locator.e5wFl3G'] = $instance;
    }
}
