<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zj8s_MdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zj8s.md' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'analyzer' => ['privates', 'App\\Service\\RegistrationAnalyzer', 'getRegistrationAnalyzerService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'notificationService' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
        ], [
            'analyzer' => 'App\\Service\\RegistrationAnalyzer',
            'entityManager' => '?',
            'notificationService' => 'App\\Service\\NotificationService',
        ]);

        if (isset($container->privates['.service_locator.Zj8s.md'])) {
            return $container->privates['.service_locator.Zj8s.md'];
        }

        return $container->privates['.service_locator.Zj8s.md'] = $instance;
    }
}
