<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J8Z7VmvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J8Z7Vmv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'async' => ['privates', 'messenger.transport.async', 'getMessenger_Transport_AsyncService', true],
            'messenger.transport.async' => ['privates', 'messenger.transport.async', 'getMessenger_Transport_AsyncService', true],
            'messenger.transport.sync' => ['privates', 'messenger.transport.sync', 'getMessenger_Transport_SyncService', true],
            'sync' => ['privates', 'messenger.transport.sync', 'getMessenger_Transport_SyncService', true],
        ], [
            'async' => '?',
            'messenger.transport.async' => '?',
            'messenger.transport.sync' => '?',
            'sync' => '?',
        ]);

        if (isset($container->privates['.service_locator.J8Z7Vmv'])) {
            return $container->privates['.service_locator.J8Z7Vmv'];
        }

        return $container->privates['.service_locator.J8Z7Vmv'] = $instance;
    }
}
