<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LPKOSZgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lPKOSZg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'document' => ['privates', '.errored..service_locator.lPKOSZg.App\\Entity\\Document', NULL, 'Cannot autowire service ".service_locator.lPKOSZg": it needs an instance of "App\\Entity\\Document" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'document' => 'App\\Entity\\Document',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.lPKOSZg'])) {
            return $container->privates['.service_locator.lPKOSZg'];
        }

        return $container->privates['.service_locator.lPKOSZg'] = $instance;
    }
}
