<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PtZS0QyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PtZS0Qy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'documentRepository' => ['privates', 'App\\Repository\\DocumentRepository', 'getDocumentRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'documentRepository' => 'App\\Repository\\DocumentRepository',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.PtZS0Qy'])) {
            return $container->privates['.service_locator.PtZS0Qy'];
        }

        return $container->privates['.service_locator.PtZS0Qy'] = $instance;
    }
}
