<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F3sEBZ6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f3sEBZ6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'entrepriseRepository' => ['privates', 'App\\Repository\\EntrepriseRepository', 'getEntrepriseRepositoryService', true],
            'historyService' => ['privates', 'App\\Service\\HistoryService', 'getHistoryServiceService', true],
        ], [
            'entityManager' => '?',
            'entrepriseRepository' => 'App\\Repository\\EntrepriseRepository',
            'historyService' => 'App\\Service\\HistoryService',
        ]);

        if (isset($container->privates['.service_locator.f3sEBZ6'])) {
            return $container->privates['.service_locator.f3sEBZ6'];
        }

        return $container->privates['.service_locator.f3sEBZ6'] = $instance;
    }
}
