<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KgrbiP6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KgrbiP6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'entreprise' => ['privates', '.errored..service_locator.KgrbiP6.App\\Entity\\Entreprise', NULL, 'Cannot autowire service ".service_locator.KgrbiP6": it needs an instance of "App\\Entity\\Entreprise" but this type has been excluded in "config/services.yaml".'],
            'historyService' => ['privates', 'App\\Service\\HistoryService', 'getHistoryServiceService', true],
        ], [
            'entityManager' => '?',
            'entreprise' => 'App\\Entity\\Entreprise',
            'historyService' => 'App\\Service\\HistoryService',
        ]);

        if (isset($container->privates['.service_locator.KgrbiP6'])) {
            return $container->privates['.service_locator.KgrbiP6'];
        }

        return $container->privates['.service_locator.KgrbiP6'] = $instance;
    }
}
