<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PWBV4kwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pWBV4kw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pWBV4kw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'documentRepo' => ['privates', 'App\\Repository\\DocumentRepository', 'getDocumentRepositoryService', true],
            'entrepriseRepo' => ['privates', 'App\\Repository\\EntrepriseRepository', 'getEntrepriseRepositoryService', true],
        ], [
            'documentRepo' => 'App\\Repository\\DocumentRepository',
            'entrepriseRepo' => 'App\\Repository\\EntrepriseRepository',
        ]);
    }
}
