<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WDF7YKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WDF7Y_k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'utilisateur' => ['privates', '.errored..service_locator.WDF7Y_k.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.WDF7Y_k": it needs an instance of "App\\Entity\\Utilisateur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'utilisateur' => 'App\\Entity\\Utilisateur',
        ]);

        if (isset($container->privates['.service_locator.WDF7Y_k'])) {
            return $container->privates['.service_locator.WDF7Y_k'];
        }

        return $container->privates['.service_locator.WDF7Y_k'] = $instance;
    }
}
