<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mf9VsUrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mf9VsUr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entrepriseRepository' => ['privates', 'App\\Repository\\EntrepriseRepository', 'getEntrepriseRepositoryService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'entrepriseRepository' => 'App\\Repository\\EntrepriseRepository',
            'mailer' => '?',
        ]);

        if (isset($container->privates['.service_locator.Mf9VsUr'])) {
            return $container->privates['.service_locator.Mf9VsUr'];
        }

        return $container->privates['.service_locator.Mf9VsUr'] = $instance;
    }
}
