<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WIHfiGFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WIHfiGF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'historyService' => ['privates', 'App\\Service\\HistoryService', 'getHistoryServiceService', true],
        ], [
            'entityManager' => '?',
            'historyService' => 'App\\Service\\HistoryService',
        ]);

        if (isset($container->privates['.service_locator.WIHfiGF'])) {
            return $container->privates['.service_locator.WIHfiGF'];
        }

        return $container->privates['.service_locator.WIHfiGF'] = $instance;
    }
}
