<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q8RAY9AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q8RAY9A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q8RAY9A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'document' => ['privates', '.errored..service_locator.Q8RAY9A.App\\Entity\\Document', NULL, 'Cannot autowire service ".service_locator.Q8RAY9A": it needs an instance of "App\\Entity\\Document" but this type has been excluded in "config/services.yaml".'],
        ], [
            'document' => 'App\\Entity\\Document',
        ]);
    }
}
