<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DliGwWt.App\Entity\Document' shared service.
     *
     * @return \App\Entity\Document
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DliGwWt": it needs an instance of "App\\Entity\\Document" but this type has been excluded in "config/services.yaml".');
    }
}
