<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentNotificationListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\DocumentNotificationListener' shared autowired service.
     *
     * @return \App\EventListener\DocumentNotificationListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'DocumentNotificationListener.php';

        $a = ($container->privates['App\\Service\\NotificationService'] ?? $container->load('getNotificationServiceService'));

        if (isset($container->privates['App\\EventListener\\DocumentNotificationListener'])) {
            return $container->privates['App\\EventListener\\DocumentNotificationListener'];
        }

        $instance = new \App\EventListener\DocumentNotificationListener($a, ($container->services['router'] ?? self::getRouterService($container)), ($container->privates['logger'] ?? self::getLoggerService($container)));

        if (isset($container->privates['App\\EventListener\\DocumentNotificationListener'])) {
            return $container->privates['App\\EventListener\\DocumentNotificationListener'];
        }

        return $container->privates['App\\EventListener\\DocumentNotificationListener'] = $instance;
    }
}
