<?php

namespace ContainerW0bl9yW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\NotificationService' shared autowired service.
     *
     * @return \App\Service\NotificationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'NotificationService.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\NotificationService'])) {
            return $container->privates['App\\Service\\NotificationService'];
        }

        $instance = new \App\Service\NotificationService($a, ($container->privates['logger'] ?? self::getLoggerService($container)));

        if (isset($container->privates['App\\Service\\NotificationService'])) {
            return $container->privates['App\\Service\\NotificationService'];
        }

        return $container->privates['App\\Service\\NotificationService'] = $instance;
    }
}
