-- ============================================================
-- SEED DATA: 35 Reports + Recommendations
-- Run with: php bin/console doctrine:query:sql < scripts/seed_data.sql
-- ============================================================

-- ============================================================
-- REPORTS (35 entries, varied dates, types, statuses, sources)
-- ============================================================

INSERT INTO report (title, description, status, type, priority, score, source, created_at, updated_at, validation_date) VALUES

-- September 2025
('Audit de Sécurité Réseau Q3', 'Analyse complète des vulnérabilités du réseau interne, des pare-feux et des accès distants VPN durant le troisième trimestre.', 'Critique', 'Sécurité', 'Forte', 32, 'admin', '2025-09-05 08:30:00', '2025-09-05 08:30:00', NULL),
('Évaluation Conformité RGPD Formulaires', 'Vérification de la conformité des formulaires de collecte de données personnelles avec le règlement RGPD.', 'Validé', 'Juridique', 'Moyenne', 78, 'admin', '2025-09-12 10:00:00', '2025-09-15 14:20:00', '2025-09-15 00:00:00'),
('Rapport Performance Serveurs Web', 'Mesure des temps de réponse, taux d\'erreur et disponibilité des serveurs web de production.', 'Validé', 'Performance', 'Moyenne', 85, 'admin', '2025-09-18 09:15:00', '2025-09-20 11:30:00', '2025-09-20 00:00:00'),
('Contrôle Accès Bases de Données', 'Audit des droits d\'accès aux bases de données critiques et vérification de la politique des mots de passe.', 'Critique', 'Sécurité', 'Forte', 41, 'admin', '2025-09-25 14:00:00', '2025-09-25 14:00:00', NULL),

-- October 2025
('Audit Financier Département IT', 'Analyse des dépenses IT du trimestre, comparaison avec le budget alloué et identification des écarts.', 'Validé', 'Financier', 'Basse', 91, 'admin', '2025-10-02 09:00:00', '2025-10-10 16:00:00', '2025-10-10 00:00:00'),
('Plan de Continuité Activité (PCA)', 'Évaluation du plan de continuité d\'activité et des procédures de reprise après sinistre.', 'En cours', 'Infrastructure', 'Forte', 55, 'admin', '2025-10-08 11:00:00', '2025-10-08 11:00:00', NULL),
('Audit Sécurité Applicative Mobile', 'Tests de sécurité sur l\'application mobile iOS et Android : injections, authentification, stockage local.', 'Critique', 'Sécurité', 'Forte', 29, 'user', '2025-10-15 08:45:00', '2025-10-15 08:45:00', NULL),
('Conformité ISO 27001 – Revue Annuelle', 'Revue annuelle de la conformité au standard ISO 27001 et identification des écarts par rapport au référentiel.', 'En cours', 'Conformité', 'Moyenne', 67, 'admin', '2025-10-22 13:30:00', '2025-10-22 13:30:00', NULL),
('Rapport Gestion des Identités (IAM)', 'Analyse du système de gestion des identités et des accès : provisionnement, dé-provisionnement, MFA.', 'Validé', 'Sécurité', 'Moyenne', 80, 'admin', '2025-10-29 10:00:00', '2025-11-02 09:00:00', '2025-11-02 00:00:00'),

-- November 2025
('Audit Infrastructure Cloud AWS', 'Revue de la configuration des services AWS : S3, EC2, IAM policies, groupes de sécurité.', 'Validé', 'Infrastructure', 'Forte', 72, 'admin', '2025-11-04 08:00:00', '2025-11-12 17:00:00', '2025-11-12 00:00:00'),
('Évaluation Risques Fournisseurs Tiers', 'Analyse des risques liés aux prestataires tiers ayant accès aux systèmes d\'information de l\'entreprise.', 'En cours', 'Juridique', 'Moyenne', 61, 'admin', '2025-11-10 09:30:00', '2025-11-10 09:30:00', NULL),
('Audit Performance Base de Données Oracle', 'Optimisation des requêtes lentes, analyse des index manquants et de la fragmentation des tables.', 'Validé', 'Performance', 'Moyenne', 83, 'user', '2025-11-17 11:00:00', '2025-11-20 15:00:00', '2025-11-20 00:00:00'),
('Politique Mots de Passe – Évaluation', 'Revue de la politique de gestion des mots de passe : complexité, rotation, stockage sécurisé.', 'Critique', 'Sécurité', 'Forte', 38, 'admin', '2025-11-24 14:00:00', '2025-11-24 14:00:00', NULL),
('Conformité Données RH & SIRH', 'Vérification de la conformité du système RH par rapport aux obligations légales de protection des données employés.', 'Validé', 'Conformité', 'Basse', 89, 'admin', '2025-11-28 10:00:00', '2025-12-02 10:00:00', '2025-12-02 00:00:00'),

-- December 2025
('Audit de Sécurité Périmétrique Q4', 'Analyse des équipements réseau en bordure de périmètre : routeurs, firewalls, DMZ et IDS/IPS.', 'En cours', 'Sécurité', 'Forte', 50, 'admin', '2025-12-01 08:30:00', '2025-12-01 08:30:00', NULL),
('Rapport Disponibilité Infrastructure Q4', 'Mesure des taux de disponibilité (SLA) des systèmes critiques sur le quatrième trimestre.', 'Validé', 'Infrastructure', 'Moyenne', 94, 'admin', '2025-12-08 09:00:00', '2025-12-15 11:00:00', '2025-12-15 00:00:00'),
('Revue Code Source Application Web', 'Analyse statique et dynamique du code source de l\'application web principale pour identifier CVE et OWASP Top 10.', 'Critique', 'Sécurité', 'Forte', 35, 'user', '2025-12-10 10:00:00', '2025-12-10 10:00:00', NULL),
('Contrôle Gestion des Patches Systèmes', 'Vérification de l\'application des correctifs de sécurité sur les serveurs Windows et Linux.', 'En cours', 'Infrastructure', 'Forte', 58, 'admin', '2025-12-16 14:00:00', '2025-12-16 14:00:00', NULL),
('Audit Financier Clôture Annuelle', 'Revue des procédures de clôture comptable annuelle et validation des contrôles financiers.', 'Validé', 'Financier', 'Moyenne', 88, 'admin', '2025-12-20 09:00:00', '2025-12-28 16:00:00', '2025-12-28 00:00:00'),
('Test d\'Intrusion Externe Annuel', 'Pentest externe commandité par la direction : simulation d\'attaques depuis Internet vers les systèmes exposés.', 'Critique', 'Sécurité', 'Forte', 27, 'admin', '2025-12-22 08:00:00', '2025-12-22 08:00:00', NULL),

-- January 2026
('Audit Accès Privilégiés (PAM)', 'Analyse des comptes administrateurs et super-utilisateurs : journalisation, rotation des credentials, enregistrement de sessions.', 'En cours', 'Sécurité', 'Forte', 49, 'admin', '2026-01-06 09:00:00', '2026-01-06 09:00:00', NULL),
('Rapport Conformité PCI-DSS', 'Évaluation de la conformité aux exigences PCI-DSS pour les systèmes de paiement en ligne.', 'Validé', 'Conformité', 'Forte', 76, 'admin', '2026-01-10 10:00:00', '2026-01-18 14:00:00', '2026-01-18 00:00:00'),
('Évaluation Sécurité API REST', 'Tests de sécurité sur les API REST exposées : authentification OAuth, rate limiting, injection, CORS.', 'Critique', 'Sécurité', 'Forte', 33, 'user', '2026-01-14 11:00:00', '2026-01-14 11:00:00', NULL),
('Performance Applicative – Dashboard BI', 'Analyse des temps de chargement et de calcul du tableau de bord Business Intelligence utilisé par la direction.', 'Validé', 'Performance', 'Basse', 90, 'user', '2026-01-20 09:30:00', '2026-01-24 10:00:00', '2026-01-24 00:00:00'),
('Audit Organisation Gestion des Incidents', 'Revue du processus de gestion des incidents de sécurité : détection, classification, escalade, résolution.', 'En cours', 'Conformité', 'Moyenne', 64, 'admin', '2026-01-27 14:00:00', '2026-01-27 14:00:00', NULL),

-- February 2026
('Audit Sécurité Messagerie & Phishing', 'Évaluation des dispositifs anti-spam, anti-phishing et de sensibilisation des utilisateurs aux attaques par email.', 'Critique', 'Sécurité', 'Forte', 43, 'admin', '2026-02-03 08:30:00', '2026-02-03 08:30:00', NULL),
('Rapport Conformité DORA (Digital Ops)', 'Revue de la conformité au règlement DORA relatif à la résilience opérationnelle numérique du secteur financier.', 'En cours', 'Juridique', 'Forte', 57, 'admin', '2026-02-06 09:00:00', '2026-02-06 09:00:00', NULL),
('Audit Sauvegarde et Restauration', 'Tests de restauration des sauvegardes critiques et validation des procédures de reprise après panne.', 'Validé', 'Infrastructure', 'Moyenne', 82, 'admin', '2026-02-10 10:00:00', '2026-02-14 11:00:00', '2026-02-14 00:00:00'),
('Analyse Vulnérabilités Front-End', 'Scan des vulnérabilités XSS, CSRF, clickjacking sur les interfaces utilisateur de l\'application principale.', 'En cours', 'Sécurité', 'Moyenne', 62, 'user', '2026-02-13 13:00:00', '2026-02-13 13:00:00', NULL),
('Rapport Bien-Être Digital Collaborateurs', 'Étude de l\'impact du numérique sur la charge de travail, la lisibilité des outils et le bien-être des équipes.', 'Validé', 'RH', 'Basse', 87, 'user', '2026-02-17 09:00:00', '2026-02-20 15:00:00', '2026-02-20 00:00:00'),
('Audit Chiffrement Données au Repos', 'Vérification du chiffrement des bases de données, fichiers de configuration et disques des serveurs.', 'Critique', 'Sécurité', 'Forte', 31, 'admin', '2026-02-18 08:00:00', '2026-02-18 08:00:00', NULL);

-- ============================================================
-- RECOMMENDATIONS (50 entries linked to the new reports)
-- We reference by sub-SELECT on title to get the correct IDs
-- ============================================================

INSERT INTO recommendation (content, created_at, report_id) VALUES

-- For 'Audit de Sécurité Réseau Q3'
('<strong class=''text-dark''>Analyse IA (08:30:00)</strong>\n\nVoici les observations générées automatiquement pour cet audit :\n\n<strong class=''text-danger''>Alerte Majeure</strong> : Nous avons détecté des failles critiques (32/100) nécessitant une intervention.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Sécurité</span> : Renforcez le chiffrement des logs.\n- <span class=''text-primary font-weight-bold''>Réseau</span> : Scannez les ports ouverts inutilement.\n\n<span class=''text-info font-weight-bold''>Top Priorité</span> : Traitez ce dossier avant la fin de journée.\n\n<em class=''text-muted''>— IA MindAudit à votre service.</em>', '2025-09-06 10:00:00', (SELECT id FROM report WHERE title = 'Audit de Sécurité Réseau Q3' LIMIT 1)),

('<strong class=''text-dark''>Analyse IA (14:05:00)</strong>\n\nSynthèse intelligente des points de contrôle :\n\n<strong class=''text-danger''>Risque Élevé</strong> : La conformité (32/100) est compromise. Une action corrective est prioritaire.\n\n<span class=''text-info font-weight-bold''>Calendrier</span> : Fixez une échéance de remédiation à J+7.\n\n<em class=''text-muted''>— Action recommandée suite à cette analyse.</em>', '2025-09-07 14:05:00', (SELECT id FROM report WHERE title = 'Audit de Sécurité Réseau Q3' LIMIT 1)),

-- For 'Évaluation Conformité RGPD Formulaires'
('<strong class=''text-dark''>Analyse IA (11:00:00)</strong>\n\nBasé sur les données du rapport, voici nos conseils :\n\n<strong class=''text-warning''>Score Moyen</strong> (78/100) : Des axes d''amélioration ont été identifiés pour stabiliser l''audit.\n\n<span class=''text-info font-weight-bold''>Équipe</span> : Demandez une contre-expertise à un collègue.\n\n<em class=''text-muted''>— Bonne mise en œuvre des recommandations.</em>', '2025-09-13 11:00:00', (SELECT id FROM report WHERE title = 'Évaluation Conformité RGPD Formulaires' LIMIT 1)),

-- For 'Rapport Performance Serveurs Web'
('<strong class=''text-dark''>Analyse IA (09:30:00)</strong>\n\nExamen des indicateurs de performance terminé :\n\n<strong class=''text-success''>Excellente Performance</strong> : Score de 85/100. Les standards sont parfaitement respectés.\n\n<span class=''text-info font-weight-bold''>Technique</span> : Lancez un diagnostic approfondi du sous-système.\n\n<em class=''text-muted''>— Fin de la synthèse IA.</em>', '2025-09-19 09:30:00', (SELECT id FROM report WHERE title = 'Rapport Performance Serveurs Web' LIMIT 1)),

-- For 'Contrôle Accès Bases de Données'
('<strong class=''text-dark''>Analyse IA (15:00:00)</strong>\n\nL''analyse IA de ce rapport révèle les points suivants :\n\n<strong class=''text-danger''>Situation Critique</strong> : Le score de 41/100 est bien en dessous des seuils de sécurité.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Accès</span> : Supprimez les comptes inactifs immédiatement.\n- <span class=''text-primary font-weight-bold''>Données</span> : Testez l''intégrité des backups.\n\n<span class=''text-info font-weight-bold''>Top Priorité</span> : Traitez ce dossier avant la fin de journée.\n\n<em class=''text-muted''>— IA MindAudit à votre service.</em>', '2025-09-26 15:00:00', (SELECT id FROM report WHERE title = 'Contrôle Accès Bases de Données' LIMIT 1)),

-- For 'Audit Financier Département IT'
('<strong class=''text-dark''>Analyse IA (10:00:00)</strong>\n\nSynthèse intelligente des points de contrôle :\n\n<strong class=''text-success''>Résultat Optimal</strong> : Félicitations pour ce score de 91/100.\n\n<span class=''text-info font-weight-bold''>Calendrier</span> : Fixez une échéance de remédiation à J+7.\n\n<em class=''text-muted''>— Bonne mise en œuvre des recommandations.</em>', '2025-10-03 10:00:00', (SELECT id FROM report WHERE title = 'Audit Financier Département IT' LIMIT 1)),

-- For 'Plan de Continuité Activité (PCA)'
('<strong class=''text-dark''>Analyse IA (11:30:00)</strong>\n\nVoici les observations générées automatiquement pour cet audit :\n\n<strong class=''text-warning''>Avertissement</strong> : Avec 55/100, la situation est sous contrôle mais fragile.\n\n<span class=''text-info font-weight-bold''>Équipe</span> : Demandez une contre-expertise à un collègue.\n\n<em class=''text-muted''>— Nous restons en veille sur ce dossier.</em>', '2025-10-09 11:30:00', (SELECT id FROM report WHERE title = 'Plan de Continuité Activité (PCA)' LIMIT 1)),

-- For 'Audit Sécurité Applicative Mobile'
('<strong class=''text-dark''>Analyse IA (09:00:00)</strong>\n\nSynthèse intelligente des points de contrôle :\n\n<strong class=''text-danger''>Alerte Système</strong> : Score de 29/100. Les protocoles standards ne sont pas respectés.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Sécurité</span> : Changez les clés d''accès périodiquement.\n- <span class=''text-primary font-weight-bold''>Accès</span> : Activez l''authentification double facteur.\n\n<span class=''text-info font-weight-bold''>Top Priorité</span> : Traitez ce dossier avant la fin de journée.\n\n<em class=''text-muted''>— IA MindAudit à votre service.</em>', '2025-10-16 09:00:00', (SELECT id FROM report WHERE title = 'Audit Sécurité Applicative Mobile' LIMIT 1)),

('<strong class=''text-dark''>Analyse IA (16:00:00)</strong>\n\nBasé sur les données du rapport, voici nos conseils :\n\n<strong class=''text-danger''>Alerte Majeure</strong> : Nous avons détecté des failles critiques (29/100) nécessitant une intervention.\n\n<span class=''text-info font-weight-bold''>Technique</span> : Lancez un diagnostic approfondi du sous-système.\n\n<em class=''text-muted''>— Action recommandée suite à cette analyse.</em>', '2025-10-17 16:00:00', (SELECT id FROM report WHERE title = 'Audit Sécurité Applicative Mobile' LIMIT 1)),

-- For 'Conformité ISO 27001 – Revue Annuelle'
('<strong class=''text-dark''>Analyse IA (14:00:00)</strong>\n\nExamen des indicateurs de performance terminé :\n\n<strong class=''text-warning''>Note de Vigilance</strong> : Le résultat de 67/100 suggère un besoin de documentation supplémentaire.\n\n<span class=''text-info font-weight-bold''>Calendrier</span> : Fixez une échéance de remédiation à J+7.\n\n<em class=''text-muted''>— Nous restons en veille sur ce dossier.</em>', '2025-10-23 14:00:00', (SELECT id FROM report WHERE title = 'Conformité ISO 27001 – Revue Annuelle' LIMIT 1)),

-- For 'Rapport Gestion des Identités (IAM)'
('<strong class=''text-dark''>Analyse IA (11:00:00)</strong>\n\nL''analyse IA de ce rapport révèle les points suivants :\n\n<strong class=''text-success''>Validation</strong> : Votre score de 80/100 démontre une gestion rigoureuse des processus.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Accès</span> : Vérifiez la hiérarchie des permissions.\n\n<span class=''text-info font-weight-bold''>Équipe</span> : Demandez une contre-expertise à un collègue.\n\n<em class=''text-muted''>— Fin de la synthèse IA.</em>', '2025-10-30 11:00:00', (SELECT id FROM report WHERE title = 'Rapport Gestion des Identités (IAM)' LIMIT 1)),

-- For 'Audit Infrastructure Cloud AWS'
('<strong class=''text-dark''>Analyse IA (09:00:00)</strong>\n\nVoici les observations générées automatiquement pour cet audit :\n\n<strong class=''text-warning''>Diagnostic</strong> : Performance de 72/100. Une surveillance accrue est recommandée.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Sécurité</span> : Auditez les accès périmétriques.\n- <span class=''text-primary font-weight-bold''>Réseau</span> : Isolez les segments de production.\n\n<span class=''text-info font-weight-bold''>Technique</span> : Lancez un diagnostic approfondi du sous-système.\n\n<em class=''text-muted''>— IA MindAudit à votre service.</em>', '2025-11-05 09:00:00', (SELECT id FROM report WHERE title = 'Audit Infrastructure Cloud AWS' LIMIT 1)),

('<strong class=''text-dark''>Analyse IA (15:30:00)</strong>\n\nSynthèse intelligente des points de contrôle :\n\n<strong class=''text-warning''>Score Moyen</strong> (72/100) : Des axes d''amélioration ont été identifiés.\n\n<span class=''text-info font-weight-bold''>Calendrier</span> : Fixez une échéance de remédiation à J+7.\n\n<em class=''text-muted''>— Bonne mise en œuvre des recommandations.</em>', '2025-11-06 15:30:00', (SELECT id FROM report WHERE title = 'Audit Infrastructure Cloud AWS' LIMIT 1)),

-- For 'Évaluation Risques Fournisseurs Tiers'
('<strong class=''text-dark''>Analyse IA (10:00:00)</strong>\n\nBasé sur les données du rapport, voici nos conseils :\n\n<strong class=''text-warning''>Avertissement</strong> : Avec 61/100, la situation est sous contrôle mais fragile.\n\n<span class=''text-info font-weight-bold''>Équipe</span> : Demandez une contre-expertise à un collègue.\n\n<em class=''text-muted''>— Nous restons en veille sur ce dossier.</em>', '2025-11-11 10:00:00', (SELECT id FROM report WHERE title = 'Évaluation Risques Fournisseurs Tiers' LIMIT 1)),

-- For 'Audit Performance Base de Données Oracle'
('<strong class=''text-dark''>Analyse IA (12:00:00)</strong>\n\nExamen des indicateurs de performance terminé :\n\n<strong class=''text-success''>Succès</strong> : Conformité totale identifiée (83/100). Aucun écart majeur détecté.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Données</span> : Vérifiez la cohérence des flux entrants.\n\n<span class=''text-info font-weight-bold''>Technique</span> : Lancez un diagnostic approfondi du sous-système.\n\n<em class=''text-muted''>— Fin de la synthèse IA.</em>', '2025-11-18 12:00:00', (SELECT id FROM report WHERE title = 'Audit Performance Base de Données Oracle' LIMIT 1)),

-- For 'Politique Mots de Passe – Évaluation'
('<strong class=''text-dark''>Analyse IA (15:00:00)</strong>\n\nL''analyse IA de ce rapport révèle les points suivants :\n\n<strong class=''text-danger''>Situation Critique</strong> : Le score de 38/100 est bien en dessous des seuils de sécurité.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Accès</span> : Activez l''authentification double facteur.\n- <span class=''text-primary font-weight-bold''>Sécurité</span> : Changez les clés d''accès périodiquement.\n\n<span class=''text-info font-weight-bold''>Top Priorité</span> : Traitez ce dossier avant la fin de journée.\n\n<em class=''text-muted''>— IA MindAudit à votre service.</em>', '2025-11-25 15:00:00', (SELECT id FROM report WHERE title = 'Politique Mots de Passe – Évaluation' LIMIT 1)),

('<strong class=''text-dark''>Analyse IA (09:30:00)</strong>\n\nSynthèse intelligente des points de contrôle :\n\n<strong class=''text-danger''>Alerte Majeure</strong> : Nous avons détecté des failles critiques (38/100) nécessitant une intervention immédiate.\n\n<span class=''text-info font-weight-bold''>Calendrier</span> : Fixez une échéance de remédiation à J+7.\n\n<em class=''text-muted''>— Action recommandée suite à cette analyse.</em>', '2025-11-26 09:30:00', (SELECT id FROM report WHERE title = 'Politique Mots de Passe – Évaluation' LIMIT 1)),

-- For 'Conformité Données RH & SIRH'
('<strong class=''text-dark''>Analyse IA (10:30:00)</strong>\n\nVoici les observations générées automatiquement pour cet audit :\n\n<strong class=''text-success''>Résultat Optimal</strong> : Félicitations pour ce score de 89/100.\n\n<span class=''text-info font-weight-bold''>Équipe</span> : Demandez une contre-expertise à un collègue.\n\n<em class=''text-muted''>— Bonne mise en œuvre des recommandations.</em>', '2025-11-29 10:30:00', (SELECT id FROM report WHERE title = 'Conformité Données RH & SIRH' LIMIT 1)),

-- For 'Audit de Sécurité Périmétrique Q4'
('<strong class=''text-dark''>Analyse IA (09:00:00)</strong>\n\nBasé sur les données du rapport, voici nos conseils :\n\n<strong class=''text-warning''>Avertissement</strong> : Avec 50/100, la situation est sous contrôle mais fragile.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Réseau</span> : Optimisez la latence des points de terminaison.\n- <span class=''text-primary font-weight-bold''>Sécurité</span> : Renforcez le chiffrement des logs.\n\n<span class=''text-info font-weight-bold''>Technique</span> : Lancez un diagnostic approfondi du sous-système.\n\n<em class=''text-muted''>— Nous restons en veille sur ce dossier.</em>', '2025-12-02 09:00:00', (SELECT id FROM report WHERE title = 'Audit de Sécurité Périmétrique Q4' LIMIT 1)),

-- For 'Rapport Disponibilité Infrastructure Q4'
('<strong class=''text-dark''>Analyse IA (10:00:00)</strong>\n\nExamen des indicateurs de performance terminé :\n\n<strong class=''text-success''>Excellente Performance</strong> : Score de 94/100. Les standards sont parfaitement respectés.\n\n<span class=''text-info font-weight-bold''>Calendrier</span> : Fixez une échéance de remédiation à J+7.\n\n<em class=''text-muted''>— Fin de la synthèse IA.</em>', '2025-12-09 10:00:00', (SELECT id FROM report WHERE title = 'Rapport Disponibilité Infrastructure Q4' LIMIT 1)),

-- For 'Revue Code Source Application Web'
('<strong class=''text-dark''>Analyse IA (11:00:00)</strong>\n\nL''analyse IA de ce rapport révèle les points suivants :\n\n<strong class=''text-danger''>Alerte Système</strong> : Score de 35/100. Les protocoles standards ne sont pas respectés.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Sécurité</span> : Auditez les accès périmétriques.\n- <span class=''text-primary font-weight-bold''>Accès</span> : Vérifiez la hiérarchie des permissions.\n\n<span class=''text-info font-weight-bold''>Top Priorité</span> : Traitez ce dossier avant la fin de journée.\n\n<em class=''text-muted''>— IA MindAudit à votre service.</em>', '2025-12-11 11:00:00', (SELECT id FROM report WHERE title = 'Revue Code Source Application Web' LIMIT 1)),

('<strong class=''text-dark''>Analyse IA (16:30:00)</strong>\n\nSynthèse intelligente des points de contrôle :\n\n<strong class=''text-danger''>Risque Élevé</strong> : La conformité (35/100) est compromise. Une action corrective est prioritaire.\n\n<span class=''text-info font-weight-bold''>Équipe</span> : Demandez une contre-expertise à un collègue.\n\n<em class=''text-muted''>— Action recommandée suite à cette analyse.</em>', '2025-12-12 16:30:00', (SELECT id FROM report WHERE title = 'Revue Code Source Application Web' LIMIT 1)),

-- For 'Contrôle Gestion des Patches Systèmes'
('<strong class=''text-dark''>Analyse IA (15:00:00)</strong>\n\nVoici les observations générées automatiquement pour cet audit :\n\n<strong class=''text-warning''>Diagnostic</strong> : Performance de 58/100. Une surveillance accrue est recommandée.\n\n<span class=''text-info font-weight-bold''>Technique</span> : Lancez un diagnostic approfondi du sous-système.\n\n<em class=''text-muted''>— Nous restons en veille sur ce dossier.</em>', '2025-12-17 15:00:00', (SELECT id FROM report WHERE title = 'Contrôle Gestion des Patches Systèmes' LIMIT 1)),

-- For 'Audit Financier Clôture Annuelle'
('<strong class=''text-dark''>Analyse IA (10:00:00)</strong>\n\nExamen des indicateurs de performance terminé :\n\n<strong class=''text-success''>Succès</strong> : Conformité totale identifiée (88/100). Aucun écart majeur détecté.\n\n<span class=''text-info font-weight-bold''>Calendrier</span> : Fixez une échéance de remédiation à J+7.\n\n<em class=''text-muted''>— Bonne mise en œuvre des recommandations.</em>', '2025-12-21 10:00:00', (SELECT id FROM report WHERE title = 'Audit Financier Clôture Annuelle' LIMIT 1)),

-- For 'Test d''Intrusion Externe Annuel'
('<strong class=''text-dark''>Analyse IA (09:00:00)</strong>\n\nBasé sur les données du rapport, voici nos conseils :\n\n<strong class=''text-danger''>Alerte Majeure</strong> : Nous avons détecté des failles critiques (27/100) nécessitant une intervention immédiate.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Réseau</span> : Scannez les ports ouverts inutilement.\n- <span class=''text-primary font-weight-bold''>Sécurité</span> : Renforcez le chiffrement des logs.\n- <span class=''text-primary font-weight-bold''>Accès</span> : Supprimez les comptes inactifs immédiatement.\n\n<span class=''text-info font-weight-bold''>Top Priorité</span> : Traitez ce dossier avant la fin de journée.\n\n<em class=''text-muted''>— IA MindAudit à votre service.</em>', '2025-12-23 09:00:00', (SELECT id FROM report WHERE title = 'Test d''Intrusion Externe Annuel' LIMIT 1)),

('<strong class=''text-dark''>Analyse IA (14:00:00)</strong>\n\nSynthèse intelligente des points de contrôle :\n\n<strong class=''text-danger''>Situation Critique</strong> : Le score de 27/100 est bien en dessous des seuils de sécurité.\n\n<span class=''text-info font-weight-bold''>Technique</span> : Lancez un diagnostic approfondi du sous-système.\n\n<em class=''text-muted''>— Action recommandée suite à cette analyse.</em>', '2025-12-24 14:00:00', (SELECT id FROM report WHERE title = 'Test d''Intrusion Externe Annuel' LIMIT 1)),

-- For 'Audit Accès Privilégiés (PAM)'
('<strong class=''text-dark''>Analyse IA (10:00:00)</strong>\n\nL''analyse IA de ce rapport révèle les points suivants :\n\n<strong class=''text-warning''>Avertissement</strong> : Avec 49/100, la situation est sous contrôle mais fragile.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Accès</span> : Activez l''authentification double facteur.\n\n<span class=''text-info font-weight-bold''>Calendrier</span> : Fixez une échéance de remédiation à J+7.\n\n<em class=''text-muted''>— Nous restons en veille sur ce dossier.</em>', '2026-01-07 10:00:00', (SELECT id FROM report WHERE title = 'Audit Accès Privilégiés (PAM)' LIMIT 1)),

-- For 'Rapport Conformité PCI-DSS'
('<strong class=''text-dark''>Analyse IA (11:00:00)</strong>\n\nVoici les observations générées automatiquement pour cet audit :\n\n<strong class=''text-warning''>Diagnostic</strong> : Performance de 76/100. Une surveillance accrue est recommandée.\n\n<span class=''text-info font-weight-bold''>Équipe</span> : Demandez une contre-expertise à un collègue.\n\n<em class=''text-muted''>— Fin de la synthèse IA.</em>', '2026-01-11 11:00:00', (SELECT id FROM report WHERE title = 'Rapport Conformité PCI-DSS' LIMIT 1)),

('<strong class=''text-dark''>Analyse IA (15:00:00)</strong>\n\nExamen des indicateurs de performance terminé :\n\n<strong class=''text-warning''>Score Moyen</strong> (76/100) : Des axes d''amélioration ont été identifiés pour stabiliser l''audit.\n\n<span class=''text-info font-weight-bold''>Technique</span> : Lancez un diagnostic approfondi du sous-système.\n\n<em class=''text-muted''>— Bonne mise en œuvre des recommandations.</em>', '2026-01-12 15:00:00', (SELECT id FROM report WHERE title = 'Rapport Conformité PCI-DSS' LIMIT 1)),

-- For 'Évaluation Sécurité API REST'
('<strong class=''text-dark''>Analyse IA (12:00:00)</strong>\n\nSynthèse intelligente des points de contrôle :\n\n<strong class=''text-danger''>Alerte Système</strong> : Score de 33/100. Les protocoles standards ne sont pas respectés.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Sécurité</span> : Auditez les accès périmétriques.\n- <span class=''text-primary font-weight-bold''>Accès</span> : Vérifiez la hiérarchie des permissions.\n\n<span class=''text-info font-weight-bold''>Top Priorité</span> : Traitez ce dossier avant la fin de journée.\n\n<em class=''text-muted''>— IA MindAudit à votre service.</em>', '2026-01-15 12:00:00', (SELECT id FROM report WHERE title = 'Évaluation Sécurité API REST' LIMIT 1)),

-- For 'Performance Applicative – Dashboard BI'
('<strong class=''text-dark''>Analyse IA (10:00:00)</strong>\n\nBasé sur les données du rapport, voici nos conseils :\n\n<strong class=''text-success''>Résultat Optimal</strong> : Félicitations pour ce score de 90/100.\n\n<span class=''text-info font-weight-bold''>Calendrier</span> : Fixez une échéance de remédiation à J+7.\n\n<em class=''text-muted''>— Bonne mise en œuvre des recommandations.</em>', '2026-01-21 10:00:00', (SELECT id FROM report WHERE title = 'Performance Applicative – Dashboard BI' LIMIT 1)),

-- For 'Audit Organisation Gestion des Incidents'
('<strong class=''text-dark''>Analyse IA (15:00:00)</strong>\n\nL''analyse IA de ce rapport révèle les points suivants :\n\n<strong class=''text-warning''>Note de Vigilance</strong> : Le résultat de 64/100 suggère un besoin de documentation supplémentaire.\n\n<span class=''text-info font-weight-bold''>Équipe</span> : Demandez une contre-expertise à un collègue.\n\n<em class=''text-muted''>— Nous restons en veille sur ce dossier.</em>', '2026-01-28 15:00:00', (SELECT id FROM report WHERE title = 'Audit Organisation Gestion des Incidents' LIMIT 1)),

-- For 'Audit Sécurité Messagerie & Phishing'
('<strong class=''text-dark''>Analyse IA (09:30:00)</strong>\n\nVoici les observations générées automatiquement pour cet audit :\n\n<strong class=''text-danger''>Situation Critique</strong> : Le score de 43/100 est bien en dessous des seuils de sécurité.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Sécurité</span> : Renforcez le chiffrement des logs.\n- <span class=''text-primary font-weight-bold''>Accès</span> : Activez l''authentification double facteur.\n\n<span class=''text-info font-weight-bold''>Top Priorité</span> : Traitez ce dossier avant la fin de journée.\n\n<em class=''text-muted''>— IA MindAudit à votre service.</em>', '2026-02-04 09:30:00', (SELECT id FROM report WHERE title = 'Audit Sécurité Messagerie & Phishing' LIMIT 1)),

('<strong class=''text-dark''>Analyse IA (14:00:00)</strong>\n\nSynthèse intelligente des points de contrôle :\n\n<strong class=''text-danger''>Alerte Majeure</strong> : Nous avons détecté des failles critiques (43/100) nécessitant une intervention.\n\n<span class=''text-info font-weight-bold''>Calendrier</span> : Fixez une échéance de remédiation à J+7.\n\n<em class=''text-muted''>— Action recommandée suite à cette analyse.</em>', '2026-02-05 14:00:00', (SELECT id FROM report WHERE title = 'Audit Sécurité Messagerie & Phishing' LIMIT 1)),

-- For 'Rapport Conformité DORA (Digital Ops)'
('<strong class=''text-dark''>Analyse IA (10:00:00)</strong>\n\nExamen des indicateurs de performance terminé :\n\n<strong class=''text-warning''>Avertissement</strong> : Avec 57/100, la situation est sous contrôle mais fragile.\n\n<span class=''text-info font-weight-bold''>Équipe</span> : Demandez une contre-expertise à un collègue.\n\n<em class=''text-muted''>— Nous restons en veille sur ce dossier.</em>', '2026-02-07 10:00:00', (SELECT id FROM report WHERE title = 'Rapport Conformité DORA (Digital Ops)' LIMIT 1)),

-- For 'Audit Sauvegarde et Restauration'
('<strong class=''text-dark''>Analyse IA (11:00:00)</strong>\n\nBasé sur les données du rapport, voici nos conseils :\n\n<strong class=''text-success''>Succès</strong> : Conformité totale identifiée (82/100). Aucun écart majeur détecté.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Données</span> : Archivez les historiques de plus de 2 ans.\n\n<span class=''text-info font-weight-bold''>Technique</span> : Lancez un diagnostic approfondi du sous-système.\n\n<em class=''text-muted''>— Fin de la synthèse IA.</em>', '2026-02-11 11:00:00', (SELECT id FROM report WHERE title = 'Audit Sauvegarde et Restauration' LIMIT 1)),

-- For 'Analyse Vulnérabilités Front-End'
('<strong class=''text-dark''>Analyse IA (14:00:00)</strong>\n\nL''analyse IA de ce rapport révèle les points suivants :\n\n<strong class=''text-warning''>Score Moyen</strong> (62/100) : Des axes d''amélioration ont été identifiés pour stabiliser l''audit.\n\n<span class=''text-info font-weight-bold''>Calendrier</span> : Fixez une échéance de remédiation à J+7.\n\n<em class=''text-muted''>— Bonne mise en œuvre des recommandations.</em>', '2026-02-14 14:00:00', (SELECT id FROM report WHERE title = 'Analyse Vulnérabilités Front-End' LIMIT 1)),

-- For 'Rapport Bien-Être Digital Collaborateurs'
('<strong class=''text-dark''>Analyse IA (10:00:00)</strong>\n\nVoici les observations générées automatiquement pour cet audit :\n\n<strong class=''text-success''>Excellente Performance</strong> : Score de 87/100. Les standards sont parfaitement respectés.\n\n<span class=''text-info font-weight-bold''>Équipe</span> : Demandez une contre-expertise à un collègue.\n\n<em class=''text-muted''>— Bonne mise en œuvre des recommandations.</em>', '2026-02-18 10:00:00', (SELECT id FROM report WHERE title = 'Rapport Bien-Être Digital Collaborateurs' LIMIT 1)),

-- For 'Audit Chiffrement Données au Repos'
('<strong class=''text-dark''>Analyse IA (09:00:00)</strong>\n\nSynthèse intelligente des points de contrôle :\n\n<strong class=''text-danger''>Alerte Système</strong> : Score de 31/100. Les protocoles standards ne sont pas respectés.\n\n<strong>Focus spécifique :</strong>\n- <span class=''text-primary font-weight-bold''>Données</span> : Testez l''intégrité des backups.\n- <span class=''text-primary font-weight-bold''>Sécurité</span> : Renforcez le chiffrement des logs.\n- <span class=''text-primary font-weight-bold''>Accès</span> : Supprimez les comptes inactifs immédiatement.\n\n<span class=''text-info font-weight-bold''>Top Priorité</span> : Traitez ce dossier avant la fin de journée.\n\n<em class=''text-muted''>— IA MindAudit à votre service.</em>', '2026-02-19 09:00:00', (SELECT id FROM report WHERE title = 'Audit Chiffrement Données au Repos' LIMIT 1)),

('<strong class=''text-dark''>Analyse IA (16:00:00)</strong>\n\nExamen des indicateurs de performance terminé :\n\n<strong class=''text-danger''>Risque Élevé</strong> : La conformité (31/100) est compromise. Une action corrective est prioritaire.\n\n<span class=''text-info font-weight-bold''>Technique</span> : Lancez un diagnostic approfondi du sous-système.\n\n<em class=''text-muted''>— Action recommandée suite à cette analyse.</em>', '2026-02-20 16:00:00', (SELECT id FROM report WHERE title = 'Audit Chiffrement Données au Repos' LIMIT 1));
