<?php
// scripts/seed.php - Run with: php scripts/seed.php

require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Dotenv\Dotenv;

(new Dotenv())->bootEnv(__DIR__ . '/../.env');

$dsn = $_ENV['DATABASE_URL'];

// Parse the DSN
preg_match('#mysql://([^:]*):([^@]*)@([^:]+):(\d+)/([^?]+)#', $dsn, $m);
[, $user, $pass, $host, $port, $dbname] = $m;
$dbname = explode('?', $dbname)[0];

try {
    $pdo = new PDO("mysql:host=$host;port=$port;dbname=$dbname;charset=utf8mb4", $user, $pass ?: null, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ]);
    echo "✅ Connected to database: $dbname\n";
} catch (Exception $e) {
    die("❌ Connection failed: " . $e->getMessage() . "\n");
}

// ============================================================
// INSERT 35 REPORTS
// ============================================================
$reports = [
    // September 2025
    ['Audit de Sécurité Réseau Q3', 'Analyse complète des vulnérabilités du réseau interne, des pare-feux et des accès distants VPN durant le troisième trimestre.', 'Critique', 'Sécurité', 'Forte', 32, 'admin', '2025-09-05 08:30:00', null],
    ['Évaluation Conformité RGPD Formulaires', 'Vérification de la conformité des formulaires de collecte de données personnelles avec le règlement RGPD.', 'Validé', 'Juridique', 'Moyenne', 78, 'admin', '2025-09-12 10:00:00', '2025-09-15'],
    ['Rapport Performance Serveurs Web', "Mesure des temps de réponse, taux d'erreur et disponibilité des serveurs web de production.", 'Validé', 'Performance', 'Moyenne', 85, 'admin', '2025-09-18 09:15:00', '2025-09-20'],
    ['Contrôle Accès Bases de Données', "Audit des droits d'accès aux bases de données critiques et vérification de la politique des mots de passe.", 'Critique', 'Sécurité', 'Forte', 41, 'admin', '2025-09-25 14:00:00', null],

    // October 2025
    ['Audit Financier Département IT', "Analyse des dépenses IT du trimestre, comparaison avec le budget alloué et identification des écarts.", 'Validé', 'Financier', 'Basse', 91, 'admin', '2025-10-02 09:00:00', '2025-10-10'],
    ["Plan de Continuité Activité (PCA)", "Évaluation du plan de continuité d'activité et des procédures de reprise après sinistre.", 'En cours', 'Infrastructure', 'Forte', 55, 'admin', '2025-10-08 11:00:00', null],
    ['Audit Sécurité Applicative Mobile', 'Tests de sécurité sur l\'application mobile iOS et Android : injections, authentification, stockage local.', 'Critique', 'Sécurité', 'Forte', 29, 'user', '2025-10-15 08:45:00', null],
    ['Conformité ISO 27001 – Revue Annuelle', 'Revue annuelle de la conformité au standard ISO 27001 et identification des écarts par rapport au référentiel.', 'En cours', 'Conformité', 'Moyenne', 67, 'admin', '2025-10-22 13:30:00', null],
    ['Rapport Gestion des Identités (IAM)', 'Analyse du système de gestion des identités et des accès : provisionnement, dé-provisionnement, MFA.', 'Validé', 'Sécurité', 'Moyenne', 80, 'admin', '2025-10-29 10:00:00', '2025-11-02'],

    // November 2025
    ['Audit Infrastructure Cloud AWS', 'Revue de la configuration des services AWS : S3, EC2, IAM policies, groupes de sécurité.', 'Validé', 'Infrastructure', 'Forte', 72, 'admin', '2025-11-04 08:00:00', '2025-11-12'],
    ['Évaluation Risques Fournisseurs Tiers', "Analyse des risques liés aux prestataires tiers ayant accès aux systèmes d'information de l'entreprise.", 'En cours', 'Juridique', 'Moyenne', 61, 'admin', '2025-11-10 09:30:00', null],
    ['Audit Performance Base de Données Oracle', "Optimisation des requêtes lentes, analyse des index manquants et de la fragmentation des tables.", 'Validé', 'Performance', 'Moyenne', 83, 'user', '2025-11-17 11:00:00', '2025-11-20'],
    ['Politique Mots de Passe – Évaluation', 'Revue de la politique de gestion des mots de passe : complexité, rotation, stockage sécurisé.', 'Critique', 'Sécurité', 'Forte', 38, 'admin', '2025-11-24 14:00:00', null],
    ['Conformité Données RH & SIRH', 'Vérification de la conformité du système RH par rapport aux obligations légales de protection des données employés.', 'Validé', 'Conformité', 'Basse', 89, 'admin', '2025-11-28 10:00:00', '2025-12-02'],

    // December 2025
    ['Audit de Sécurité Périmétrique Q4', 'Analyse des équipements réseau en bordure de périmètre : routeurs, firewalls, DMZ et IDS/IPS.', 'En cours', 'Sécurité', 'Forte', 50, 'admin', '2025-12-01 08:30:00', null],
    ['Rapport Disponibilité Infrastructure Q4', 'Mesure des taux de disponibilité (SLA) des systèmes critiques sur le quatrième trimestre.', 'Validé', 'Infrastructure', 'Moyenne', 94, 'admin', '2025-12-08 09:00:00', '2025-12-15'],
    ['Revue Code Source Application Web', "Analyse statique et dynamique du code source de l'application web principale pour identifier CVE et OWASP Top 10.", 'Critique', 'Sécurité', 'Forte', 35, 'user', '2025-12-10 10:00:00', null],
    ['Contrôle Gestion des Patches Systèmes', 'Vérification de l\'application des correctifs de sécurité sur les serveurs Windows et Linux.', 'En cours', 'Infrastructure', 'Forte', 58, 'admin', '2025-12-16 14:00:00', null],
    ['Audit Financier Clôture Annuelle', 'Revue des procédures de clôture comptable annuelle et validation des contrôles financiers.', 'Validé', 'Financier', 'Moyenne', 88, 'admin', '2025-12-20 09:00:00', '2025-12-28'],
    ["Test d'Intrusion Externe Annuel", "Pentest externe commandité par la direction : simulation d'attaques depuis Internet vers les systèmes exposés.", 'Critique', 'Sécurité', 'Forte', 27, 'admin', '2025-12-22 08:00:00', null],

    // January 2026
    ['Audit Accès Privilégiés (PAM)', 'Analyse des comptes administrateurs et super-utilisateurs : journalisation, rotation des credentials, enregistrement de sessions.', 'En cours', 'Sécurité', 'Forte', 49, 'admin', '2026-01-06 09:00:00', null],
    ['Rapport Conformité PCI-DSS', "Évaluation de la conformité aux exigences PCI-DSS pour les systèmes de paiement en ligne.", 'Validé', 'Conformité', 'Forte', 76, 'admin', '2026-01-10 10:00:00', '2026-01-18'],
    ['Évaluation Sécurité API REST', 'Tests de sécurité sur les API REST exposées : authentification OAuth, rate limiting, injection, CORS.', 'Critique', 'Sécurité', 'Forte', 33, 'user', '2026-01-14 11:00:00', null],
    ['Performance Applicative – Dashboard BI', 'Analyse des temps de chargement et de calcul du tableau de bord Business Intelligence utilisé par la direction.', 'Validé', 'Performance', 'Basse', 90, 'user', '2026-01-20 09:30:00', '2026-01-24'],
    ['Audit Organisation Gestion des Incidents', 'Revue du processus de gestion des incidents de sécurité : détection, classification, escalade, résolution.', 'En cours', 'Conformité', 'Moyenne', 64, 'admin', '2026-01-27 14:00:00', null],

    // February 2026
    ['Audit Sécurité Messagerie & Phishing', "Évaluation des dispositifs anti-spam, anti-phishing et de sensibilisation des utilisateurs aux attaques par email.", 'Critique', 'Sécurité', 'Forte', 43, 'admin', '2026-02-03 08:30:00', null],
    ['Rapport Conformité DORA (Digital Ops)', 'Revue de la conformité au règlement DORA relatif à la résilience opérationnelle numérique du secteur financier.', 'En cours', 'Juridique', 'Forte', 57, 'admin', '2026-02-06 09:00:00', null],
    ['Audit Sauvegarde et Restauration', 'Tests de restauration des sauvegardes critiques et validation des procédures de reprise après panne.', 'Validé', 'Infrastructure', 'Moyenne', 82, 'admin', '2026-02-10 10:00:00', '2026-02-14'],
    ['Analyse Vulnérabilités Front-End', "Scan des vulnérabilités XSS, CSRF, clickjacking sur les interfaces utilisateur de l'application principale.", 'En cours', 'Sécurité', 'Moyenne', 62, 'user', '2026-02-13 13:00:00', null],
    ['Rapport Bien-Être Digital Collaborateurs', "Étude de l'impact du numérique sur la charge de travail, la lisibilité des outils et le bien-être des équipes.", 'Validé', 'RH', 'Basse', 87, 'user', '2026-02-17 09:00:00', '2026-02-20'],
    ['Audit Chiffrement Données au Repos', "Vérification du chiffrement des bases de données, fichiers de configuration et disques des serveurs.", 'Critique', 'Sécurité', 'Forte', 31, 'admin', '2026-02-18 08:00:00', null],
    ['Revue Politique de Sécurité Globale', "Évaluation complète de la charte de sécurité de l'information et des procédures opérationnelles associées.", 'En cours', 'Conformité', 'Moyenne', 68, 'admin', '2026-02-20 09:00:00', null],
    ['Audit Journaux Systèmes & SIEM', "Revue de la qualité des logs collectés et de leur corrélation dans le SIEM pour détecter les incidents.", 'En cours', 'Infrastructure', 'Moyenne', 59, 'admin', '2026-02-21 10:00:00', null],
    ['Contrôle Antivirus & EDR Endpoints', "Vérification du déploiement et de l'efficacité des solutions antivirus et EDR sur l'ensemble des postes.", 'Validé', 'Sécurité', 'Forte', 84, 'user', '2026-02-22 08:30:00', '2026-02-24'],
    ['Audit Sensibilisation Cybersécurité', "Évaluation du programme de formation et de sensibilisation à la cybersécurité pour les employés.", 'Validé', 'RH', 'Basse', 92, 'admin', '2026-02-23 09:00:00', '2026-02-25'],
];

$insertReport = $pdo->prepare(
    "INSERT INTO report (title, description, status, type, priority, score, source, created_at, updated_at, validation_date) VALUES (?,?,?,?,?,?,?,?,?,?)"
);

$reportIdMap = [];
$inserted = 0;
foreach ($reports as $r) {
    [$title, $desc, $status, $type, $priority, $score, $source, $created, $validationDate] = $r;
    $updatedAt = $created;
    if ($validationDate) {
        $updatedAt = $validationDate . ' 14:00:00';
    }
    $insertReport->execute([$title, $desc, $status, $type, $priority, $score, $source, $created, $updatedAt, $validationDate]);
    $reportIdMap[$title] = $pdo->lastInsertId();
    $inserted++;
}

echo "✅ Inserted $inserted reports.\n";

// ============================================================
// INSERT RECOMMENDATIONS
// ============================================================
$recs = [
    ['Audit de Sécurité Réseau Q3', '<strong class="text-dark">Analyse IA (08:30:00)</strong>'."\n\n".'Voici les observations générées automatiquement pour cet audit :'."\n\n".'<strong class="text-danger">Alerte Majeure</strong> : Nous avons détecté des failles critiques (32/100) nécessitant une intervention.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Sécurité</span> : Renforcez le chiffrement des logs.'."\n".'- <span class="text-primary font-weight-bold">Réseau</span> : Scannez les ports ouverts inutilement.'."\n\n".'<span class="text-info font-weight-bold">Top Priorité</span> : Traitez ce dossier avant la fin de journée.'."\n\n".'<em class="text-muted">— IA MindAudit à votre service.</em>', '2025-09-06 10:00:00'],
    ['Audit de Sécurité Réseau Q3', '<strong class="text-dark">Analyse IA (14:05:00)</strong>'."\n\n".'Synthèse intelligente des points de contrôle :'."\n\n".'<strong class="text-danger">Risque Élevé</strong> : La conformité (32/100) est compromise. Une action corrective est prioritaire.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— Action recommandée suite à cette analyse.</em>', '2025-09-07 14:05:00'],
    ['Évaluation Conformité RGPD Formulaires', '<strong class="text-dark">Analyse IA (11:00:00)</strong>'."\n\n".'Basé sur les données du rapport, voici nos conseils :'."\n\n".'<strong class="text-warning">Score Moyen</strong> (78/100) : Des axes d\'amélioration ont été identifiés pour stabiliser l\'audit.'."\n\n".'<span class="text-info font-weight-bold">Équipe</span> : Demandez une contre-expertise à un collègue.'."\n\n".'<em class="text-muted">— Bonne mise en œuvre des recommandations.</em>', '2025-09-13 11:00:00'],
    ['Rapport Performance Serveurs Web', '<strong class="text-dark">Analyse IA (09:30:00)</strong>'."\n\n".'Examen des indicateurs de performance terminé :'."\n\n".'<strong class="text-success">Excellente Performance</strong> : Score de 85/100. Les standards sont parfaitement respectés.'."\n\n".'<span class="text-info font-weight-bold">Technique</span> : Lancez un diagnostic approfondi du sous-système.'."\n\n".'<em class="text-muted">— Fin de la synthèse IA.</em>', '2025-09-19 09:30:00'],
    ['Contrôle Accès Bases de Données', '<strong class="text-dark">Analyse IA (15:00:00)</strong>'."\n\n".'L\'analyse IA de ce rapport révèle les points suivants :'."\n\n".'<strong class="text-danger">Situation Critique</strong> : Le score de 41/100 est bien en dessous des seuils de sécurité.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Accès</span> : Supprimez les comptes inactifs immédiatement.'."\n".'- <span class="text-primary font-weight-bold">Données</span> : Testez l\'intégrité des backups.'."\n\n".'<span class="text-info font-weight-bold">Top Priorité</span> : Traitez ce dossier avant la fin de journée.'."\n\n".'<em class="text-muted">— IA MindAudit à votre service.</em>', '2025-09-26 15:00:00'],
    ['Audit Financier Département IT', '<strong class="text-dark">Analyse IA (10:00:00)</strong>'."\n\n".'Synthèse intelligente des points de contrôle :'."\n\n".'<strong class="text-success">Résultat Optimal</strong> : Félicitations pour ce score de 91/100.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— Bonne mise en œuvre des recommandations.</em>', '2025-10-03 10:00:00'],
    ['Plan de Continuité Activité (PCA)', '<strong class="text-dark">Analyse IA (11:30:00)</strong>'."\n\n".'Voici les observations générées automatiquement pour cet audit :'."\n\n".'<strong class="text-warning">Avertissement</strong> : Avec 55/100, la situation est sous contrôle mais fragile.'."\n\n".'<span class="text-info font-weight-bold">Équipe</span> : Demandez une contre-expertise à un collègue.'."\n\n".'<em class="text-muted">— Nous restons en veille sur ce dossier.</em>', '2025-10-09 11:30:00'],
    ['Audit Sécurité Applicative Mobile', '<strong class="text-dark">Analyse IA (09:00:00)</strong>'."\n\n".'Synthèse intelligente des points de contrôle :'."\n\n".'<strong class="text-danger">Alerte Système</strong> : Score de 29/100. Les protocoles standards ne sont pas respectés.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Sécurité</span> : Changez les clés d\'accès périodiquement.'."\n".'- <span class="text-primary font-weight-bold">Accès</span> : Activez l\'authentification double facteur.'."\n\n".'<span class="text-info font-weight-bold">Top Priorité</span> : Traitez ce dossier avant la fin de journée.'."\n\n".'<em class="text-muted">— IA MindAudit à votre service.</em>', '2025-10-16 09:00:00'],
    ['Audit Sécurité Applicative Mobile', '<strong class="text-dark">Analyse IA (16:00:00)</strong>'."\n\n".'Basé sur les données du rapport, voici nos conseils :'."\n\n".'<strong class="text-danger">Alerte Majeure</strong> : Nous avons détecté des failles critiques (29/100) nécessitant une intervention.'."\n\n".'<span class="text-info font-weight-bold">Technique</span> : Lancez un diagnostic approfondi du sous-système.'."\n\n".'<em class="text-muted">— Action recommandée suite à cette analyse.</em>', '2025-10-17 16:00:00'],
    ['Conformité ISO 27001 – Revue Annuelle', '<strong class="text-dark">Analyse IA (14:00:00)</strong>'."\n\n".'Examen des indicateurs de performance terminé :'."\n\n".'<strong class="text-warning">Note de Vigilance</strong> : Le résultat de 67/100 suggère un besoin de documentation supplémentaire.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— Nous restons en veille sur ce dossier.</em>', '2025-10-23 14:00:00'],
    ['Rapport Gestion des Identités (IAM)', '<strong class="text-dark">Analyse IA (11:00:00)</strong>'."\n\n".'L\'analyse IA de ce rapport révèle les points suivants :'."\n\n".'<strong class="text-success">Validation</strong> : Votre score de 80/100 démontre une gestion rigoureuse des processus.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Accès</span> : Vérifiez la hiérarchie des permissions.'."\n\n".'<span class="text-info font-weight-bold">Équipe</span> : Demandez une contre-expertise à un collègue.'."\n\n".'<em class="text-muted">— Fin de la synthèse IA.</em>', '2025-10-30 11:00:00'],
    ['Audit Infrastructure Cloud AWS', '<strong class="text-dark">Analyse IA (09:00:00)</strong>'."\n\n".'Voici les observations générées automatiquement pour cet audit :'."\n\n".'<strong class="text-warning">Diagnostic</strong> : Performance de 72/100. Une surveillance accrue est recommandée.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Sécurité</span> : Auditez les accès périmétriques.'."\n".'- <span class="text-primary font-weight-bold">Réseau</span> : Isolez les segments de production.'."\n\n".'<span class="text-info font-weight-bold">Technique</span> : Lancez un diagnostic approfondi du sous-système.'."\n\n".'<em class="text-muted">— IA MindAudit à votre service.</em>', '2025-11-05 09:00:00'],
    ['Audit Infrastructure Cloud AWS', '<strong class="text-dark">Analyse IA (15:30:00)</strong>'."\n\n".'Synthèse intelligente des points de contrôle :'."\n\n".'<strong class="text-warning">Score Moyen</strong> (72/100) : Des axes d\'amélioration ont été identifiés.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— Bonne mise en œuvre des recommandations.</em>', '2025-11-06 15:30:00'],
    ['Évaluation Risques Fournisseurs Tiers', '<strong class="text-dark">Analyse IA (10:00:00)</strong>'."\n\n".'Basé sur les données du rapport, voici nos conseils :'."\n\n".'<strong class="text-warning">Avertissement</strong> : Avec 61/100, la situation est sous contrôle mais fragile.'."\n\n".'<span class="text-info font-weight-bold">Équipe</span> : Demandez une contre-expertise à un collègue.'."\n\n".'<em class="text-muted">— Nous restons en veille sur ce dossier.</em>', '2025-11-11 10:00:00'],
    ['Audit Performance Base de Données Oracle', '<strong class="text-dark">Analyse IA (12:00:00)</strong>'."\n\n".'Examen des indicateurs de performance terminé :'."\n\n".'<strong class="text-success">Succès</strong> : Conformité totale identifiée (83/100). Aucun écart majeur détecté.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Données</span> : Vérifiez la cohérence des flux entrants.'."\n\n".'<span class="text-info font-weight-bold">Technique</span> : Lancez un diagnostic approfondi du sous-système.'."\n\n".'<em class="text-muted">— Fin de la synthèse IA.</em>', '2025-11-18 12:00:00'],
    ['Politique Mots de Passe – Évaluation', '<strong class="text-dark">Analyse IA (15:00:00)</strong>'."\n\n".'L\'analyse IA de ce rapport révèle les points suivants :'."\n\n".'<strong class="text-danger">Situation Critique</strong> : Le score de 38/100 est bien en dessous des seuils de sécurité.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Accès</span> : Activez l\'authentification double facteur.'."\n".'- <span class="text-primary font-weight-bold">Sécurité</span> : Changez les clés d\'accès périodiquement.'."\n\n".'<span class="text-info font-weight-bold">Top Priorité</span> : Traitez ce dossier avant la fin de journée.'."\n\n".'<em class="text-muted">— IA MindAudit à votre service.</em>', '2025-11-25 15:00:00'],
    ['Politique Mots de Passe – Évaluation', '<strong class="text-dark">Analyse IA (09:30:00)</strong>'."\n\n".'Synthèse intelligente des points de contrôle :'."\n\n".'<strong class="text-danger">Alerte Majeure</strong> : Nous avons détecté des failles critiques (38/100) nécessitant une intervention immédiate.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— Action recommandée suite à cette analyse.</em>', '2025-11-26 09:30:00'],
    ['Conformité Données RH & SIRH', '<strong class="text-dark">Analyse IA (10:30:00)</strong>'."\n\n".'Voici les observations générées automatiquement pour cet audit :'."\n\n".'<strong class="text-success">Résultat Optimal</strong> : Félicitations pour ce score de 89/100.'."\n\n".'<span class="text-info font-weight-bold">Équipe</span> : Demandez une contre-expertise à un collègue.'."\n\n".'<em class="text-muted">— Bonne mise en œuvre des recommandations.</em>', '2025-11-29 10:30:00'],
    ['Audit de Sécurité Périmétrique Q4', '<strong class="text-dark">Analyse IA (09:00:00)</strong>'."\n\n".'Basé sur les données du rapport, voici nos conseils :'."\n\n".'<strong class="text-warning">Avertissement</strong> : Avec 50/100, la situation est sous contrôle mais fragile.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Réseau</span> : Optimisez la latence des points de terminaison.'."\n".'- <span class="text-primary font-weight-bold">Sécurité</span> : Renforcez le chiffrement des logs.'."\n\n".'<span class="text-info font-weight-bold">Technique</span> : Lancez un diagnostic approfondi du sous-système.'."\n\n".'<em class="text-muted">— Nous restons en veille sur ce dossier.</em>', '2025-12-02 09:00:00'],
    ['Rapport Disponibilité Infrastructure Q4', '<strong class="text-dark">Analyse IA (10:00:00)</strong>'."\n\n".'Examen des indicateurs de performance terminé :'."\n\n".'<strong class="text-success">Excellente Performance</strong> : Score de 94/100. Les standards sont parfaitement respectés.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— Fin de la synthèse IA.</em>', '2025-12-09 10:00:00'],
    ['Revue Code Source Application Web', '<strong class="text-dark">Analyse IA (11:00:00)</strong>'."\n\n".'L\'analyse IA de ce rapport révèle les points suivants :'."\n\n".'<strong class="text-danger">Alerte Système</strong> : Score de 35/100. Les protocoles standards ne sont pas respectés.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Sécurité</span> : Auditez les accès périmétriques.'."\n".'- <span class="text-primary font-weight-bold">Accès</span> : Vérifiez la hiérarchie des permissions.'."\n\n".'<span class="text-info font-weight-bold">Top Priorité</span> : Traitez ce dossier avant la fin de journée.'."\n\n".'<em class="text-muted">— IA MindAudit à votre service.</em>', '2025-12-11 11:00:00'],
    ['Revue Code Source Application Web', '<strong class="text-dark">Analyse IA (16:30:00)</strong>'."\n\n".'Synthèse intelligente des points de contrôle :'."\n\n".'<strong class="text-danger">Risque Élevé</strong> : La conformité (35/100) est compromise. Une action corrective est prioritaire.'."\n\n".'<span class="text-info font-weight-bold">Équipe</span> : Demandez une contre-expertise à un collègue.'."\n\n".'<em class="text-muted">— Action recommandée suite à cette analyse.</em>', '2025-12-12 16:30:00'],
    ['Contrôle Gestion des Patches Systèmes', '<strong class="text-dark">Analyse IA (15:00:00)</strong>'."\n\n".'Voici les observations générées automatiquement pour cet audit :'."\n\n".'<strong class="text-warning">Diagnostic</strong> : Performance de 58/100. Une surveillance accrue est recommandée.'."\n\n".'<span class="text-info font-weight-bold">Technique</span> : Lancez un diagnostic approfondi du sous-système.'."\n\n".'<em class="text-muted">— Nous restons en veille sur ce dossier.</em>', '2025-12-17 15:00:00'],
    ['Audit Financier Clôture Annuelle', '<strong class="text-dark">Analyse IA (10:00:00)</strong>'."\n\n".'Examen des indicateurs de performance terminé :'."\n\n".'<strong class="text-success">Succès</strong> : Conformité totale identifiée (88/100). Aucun écart majeur détecté.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— Bonne mise en œuvre des recommandations.</em>', '2025-12-21 10:00:00'],
    ["Test d'Intrusion Externe Annuel", '<strong class="text-dark">Analyse IA (09:00:00)</strong>'."\n\n".'Basé sur les données du rapport, voici nos conseils :'."\n\n".'<strong class="text-danger">Alerte Majeure</strong> : Nous avons détecté des failles critiques (27/100) nécessitant une intervention immédiate.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Réseau</span> : Scannez les ports ouverts inutilement.'."\n".'- <span class="text-primary font-weight-bold">Sécurité</span> : Renforcez le chiffrement des logs.'."\n".'- <span class="text-primary font-weight-bold">Accès</span> : Supprimez les comptes inactifs immédiatement.'."\n\n".'<span class="text-info font-weight-bold">Top Priorité</span> : Traitez ce dossier avant la fin de journée.'."\n\n".'<em class="text-muted">— IA MindAudit à votre service.</em>', '2025-12-23 09:00:00'],
    ["Test d'Intrusion Externe Annuel", '<strong class="text-dark">Analyse IA (14:00:00)</strong>'."\n\n".'Synthèse intelligente des points de contrôle :'."\n\n".'<strong class="text-danger">Situation Critique</strong> : Le score de 27/100 est bien en dessous des seuils de sécurité.'."\n\n".'<span class="text-info font-weight-bold">Technique</span> : Lancez un diagnostic approfondi du sous-système.'."\n\n".'<em class="text-muted">— Action recommandée suite à cette analyse.</em>', '2025-12-24 14:00:00'],
    ['Audit Accès Privilégiés (PAM)', '<strong class="text-dark">Analyse IA (10:00:00)</strong>'."\n\n".'L\'analyse IA de ce rapport révèle les points suivants :'."\n\n".'<strong class="text-warning">Avertissement</strong> : Avec 49/100, la situation est sous contrôle mais fragile.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Accès</span> : Activez l\'authentification double facteur.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— Nous restons en veille sur ce dossier.</em>', '2026-01-07 10:00:00'],
    ['Rapport Conformité PCI-DSS', '<strong class="text-dark">Analyse IA (11:00:00)</strong>'."\n\n".'Voici les observations générées automatiquement pour cet audit :'."\n\n".'<strong class="text-warning">Diagnostic</strong> : Performance de 76/100. Une surveillance accrue est recommandée.'."\n\n".'<span class="text-info font-weight-bold">Équipe</span> : Demandez une contre-expertise à un collègue.'."\n\n".'<em class="text-muted">— Fin de la synthèse IA.</em>', '2026-01-11 11:00:00'],
    ['Rapport Conformité PCI-DSS', '<strong class="text-dark">Analyse IA (15:00:00)</strong>'."\n\n".'Examen des indicateurs de performance terminé :'."\n\n".'<strong class="text-warning">Score Moyen</strong> (76/100) : Des axes d\'amélioration ont été identifiés pour stabiliser l\'audit.'."\n\n".'<span class="text-info font-weight-bold">Technique</span> : Lancez un diagnostic approfondi du sous-système.'."\n\n".'<em class="text-muted">— Bonne mise en œuvre des recommandations.</em>', '2026-01-12 15:00:00'],
    ['Évaluation Sécurité API REST', '<strong class="text-dark">Analyse IA (12:00:00)</strong>'."\n\n".'Synthèse intelligente des points de contrôle :'."\n\n".'<strong class="text-danger">Alerte Système</strong> : Score de 33/100. Les protocoles standards ne sont pas respectés.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Sécurité</span> : Auditez les accès périmétriques.'."\n".'- <span class="text-primary font-weight-bold">Accès</span> : Vérifiez la hiérarchie des permissions.'."\n\n".'<span class="text-info font-weight-bold">Top Priorité</span> : Traitez ce dossier avant la fin de journée.'."\n\n".'<em class="text-muted">— IA MindAudit à votre service.</em>', '2026-01-15 12:00:00'],
    ['Performance Applicative – Dashboard BI', '<strong class="text-dark">Analyse IA (10:00:00)</strong>'."\n\n".'Basé sur les données du rapport, voici nos conseils :'."\n\n".'<strong class="text-success">Résultat Optimal</strong> : Félicitations pour ce score de 90/100.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— Bonne mise en œuvre des recommandations.</em>', '2026-01-21 10:00:00'],
    ['Audit Organisation Gestion des Incidents', '<strong class="text-dark">Analyse IA (15:00:00)</strong>'."\n\n".'L\'analyse IA de ce rapport révèle les points suivants :'."\n\n".'<strong class="text-warning">Note de Vigilance</strong> : Le résultat de 64/100 suggère un besoin de documentation supplémentaire.'."\n\n".'<span class="text-info font-weight-bold">Équipe</span> : Demandez une contre-expertise à un collègue.'."\n\n".'<em class="text-muted">— Nous restons en veille sur ce dossier.</em>', '2026-01-28 15:00:00'],
    ['Audit Sécurité Messagerie & Phishing', '<strong class="text-dark">Analyse IA (09:30:00)</strong>'."\n\n".'Voici les observations générées automatiquement pour cet audit :'."\n\n".'<strong class="text-danger">Situation Critique</strong> : Le score de 43/100 est bien en dessous des seuils de sécurité.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Sécurité</span> : Renforcez le chiffrement des logs.'."\n".'- <span class="text-primary font-weight-bold">Accès</span> : Activez l\'authentification double facteur.'."\n\n".'<span class="text-info font-weight-bold">Top Priorité</span> : Traitez ce dossier avant la fin de journée.'."\n\n".'<em class="text-muted">— IA MindAudit à votre service.</em>', '2026-02-04 09:30:00'],
    ['Audit Sécurité Messagerie & Phishing', '<strong class="text-dark">Analyse IA (14:00:00)</strong>'."\n\n".'Synthèse intelligente des points de contrôle :'."\n\n".'<strong class="text-danger">Alerte Majeure</strong> : Nous avons détecté des failles critiques (43/100) nécessitant une intervention.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— Action recommandée suite à cette analyse.</em>', '2026-02-05 14:00:00'],
    ['Rapport Conformité DORA (Digital Ops)', '<strong class="text-dark">Analyse IA (10:00:00)</strong>'."\n\n".'Examen des indicateurs de performance terminé :'."\n\n".'<strong class="text-warning">Avertissement</strong> : Avec 57/100, la situation est sous contrôle mais fragile.'."\n\n".'<span class="text-info font-weight-bold">Équipe</span> : Demandez une contre-expertise à un collègue.'."\n\n".'<em class="text-muted">— Nous restons en veille sur ce dossier.</em>', '2026-02-07 10:00:00'],
    ['Audit Sauvegarde et Restauration', '<strong class="text-dark">Analyse IA (11:00:00)</strong>'."\n\n".'Basé sur les données du rapport, voici nos conseils :'."\n\n".'<strong class="text-success">Succès</strong> : Conformité totale identifiée (82/100). Aucun écart majeur détecté.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Données</span> : Archivez les historiques de plus de 2 ans.'."\n\n".'<span class="text-info font-weight-bold">Technique</span> : Lancez un diagnostic approfondi du sous-système.'."\n\n".'<em class="text-muted">— Fin de la synthèse IA.</em>', '2026-02-11 11:00:00'],
    ['Analyse Vulnérabilités Front-End', '<strong class="text-dark">Analyse IA (14:00:00)</strong>'."\n\n".'L\'analyse IA de ce rapport révèle les points suivants :'."\n\n".'<strong class="text-warning">Score Moyen</strong> (62/100) : Des axes d\'amélioration ont été identifiés pour stabiliser l\'audit.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— Bonne mise en œuvre des recommandations.</em>', '2026-02-14 14:00:00'],
    ['Rapport Bien-Être Digital Collaborateurs', '<strong class="text-dark">Analyse IA (10:00:00)</strong>'."\n\n".'Voici les observations générées automatiquement pour cet audit :'."\n\n".'<strong class="text-success">Excellente Performance</strong> : Score de 87/100. Les standards sont parfaitement respectés.'."\n\n".'<span class="text-info font-weight-bold">Équipe</span> : Demandez une contre-expertise à un collègue.'."\n\n".'<em class="text-muted">— Bonne mise en œuvre des recommandations.</em>', '2026-02-18 10:00:00'],
    ['Audit Chiffrement Données au Repos', '<strong class="text-dark">Analyse IA (09:00:00)</strong>'."\n\n".'Synthèse intelligente des points de contrôle :'."\n\n".'<strong class="text-danger">Alerte Système</strong> : Score de 31/100. Les protocoles standards ne sont pas respectés.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Données</span> : Testez l\'intégrité des backups.'."\n".'- <span class="text-primary font-weight-bold">Sécurité</span> : Renforcez le chiffrement des logs.'."\n".'- <span class="text-primary font-weight-bold">Accès</span> : Supprimez les comptes inactifs immédiatement.'."\n\n".'<span class="text-info font-weight-bold">Top Priorité</span> : Traitez ce dossier avant la fin de journée.'."\n\n".'<em class="text-muted">— IA MindAudit à votre service.</em>', '2026-02-19 09:00:00'],
    ['Audit Chiffrement Données au Repos', '<strong class="text-dark">Analyse IA (16:00:00)</strong>'."\n\n".'Examen des indicateurs de performance terminé :'."\n\n".'<strong class="text-danger">Risque Élevé</strong> : La conformité (31/100) est compromise. Une action corrective est prioritaire.'."\n\n".'<span class="text-info font-weight-bold">Technique</span> : Lancez un diagnostic approfondi du sous-système.'."\n\n".'<em class="text-muted">— Action recommandée suite à cette analyse.</em>', '2026-02-20 16:00:00'],
    ['Revue Politique de Sécurité Globale', '<strong class="text-dark">Analyse IA (10:30:00)</strong>'."\n\n".'Voici les observations générées automatiquement pour cet audit :'."\n\n".'<strong class="text-warning">Note de Vigilance</strong> : Le résultat de 68/100 suggère un besoin de documentation supplémentaire.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— Nous restons en veille sur ce dossier.</em>', '2026-02-21 10:30:00'],
    ['Audit Journaux Systèmes & SIEM', '<strong class="text-dark">Analyse IA (11:00:00)</strong>'."\n\n".'Basé sur les données du rapport, voici nos conseils :'."\n\n".'<strong class="text-warning">Avertissement</strong> : Avec 59/100, la situation est sous contrôle mais fragile.'."\n\n".'<strong>Focus spécifique :</strong>'."\n".'- <span class="text-primary font-weight-bold">Sécurité</span> : Auditez les accès périmétriques.'."\n\n".'<span class="text-info font-weight-bold">Équipe</span> : Demandez une contre-expertise à un collègue.'."\n\n".'<em class="text-muted">— Fin de la synthèse IA.</em>', '2026-02-22 11:00:00'],
    ['Contrôle Antivirus & EDR Endpoints', '<strong class="text-dark">Analyse IA (09:00:00)</strong>'."\n\n".'L\'analyse IA de ce rapport révèle les points suivants :'."\n\n".'<strong class="text-success">Succès</strong> : Conformité totale identifiée (84/100). Aucun écart majeur détecté.'."\n\n".'<span class="text-info font-weight-bold">Technique</span> : Lancez un diagnostic approfondi du sous-système.'."\n\n".'<em class="text-muted">— Bonne mise en œuvre des recommandations.</em>', '2026-02-23 09:00:00'],
    ['Audit Sensibilisation Cybersécurité', '<strong class="text-dark">Analyse IA (10:00:00)</strong>'."\n\n".'Examen des indicateurs de performance terminé :'."\n\n".'<strong class="text-success">Résultat Optimal</strong> : Félicitations pour ce score de 92/100.'."\n\n".'<span class="text-info font-weight-bold">Calendrier</span> : Fixez une échéance de remédiation à J+7.'."\n\n".'<em class="text-muted">— IA MindAudit à votre service.</em>', '2026-02-24 10:00:00'],
];

$insertRec = $pdo->prepare("INSERT INTO recommendation (content, created_at, report_id) VALUES (?, ?, ?)");

$recInserted = 0;
foreach ($recs as [$reportTitle, $content, $createdAt]) {
    if (!isset($reportIdMap[$reportTitle])) {
        echo "⚠️  Report not found for rec: $reportTitle\n";
        continue;
    }
    $insertRec->execute([$content, $createdAt, $reportIdMap[$reportTitle]]);
    $recInserted++;
}

echo "✅ Inserted $recInserted recommendations.\n";
echo "\n🎉 Seed completed! Total: $inserted reports + $recInserted recommendations.\n";
